---
# Todo add security/authentication specs
openapi: 3.0.0
info:
  description: API for the watchtower app
  version: 1.0.0
  title: Watchtower API
tags:
  - name: Users
    description: API for handling users and user authentication
paths:
  "/users":
    get:
      tags:
      - Users
      summary: Returns a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserInfoPageSchema"
  "/users/current":
    get:
      tags:
      - Users
      summary: Returns signed in user info
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserInfoSchema"
      produces:
      - application/json
  "/users/register":
    post:
      tags:
      - Users
      summary: Registers a user
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserInfoSchema"
      requestBody:
        description: User Sign Up Schema
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserSignUpSchema"
      produces:
      - application/json
  "/users/login":
    post:
      tags:
      - Users
      summary: Logs in a user
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserInfoSchema"
      requestBody:
        description: User Log In Schema
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserLoginSchema"
      produces:
      - application/json
  "/users/logout":
    get:
      tags:
      - Users
      summary: Logs out a user
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SuccessMessageSchema"
      produces:
      - application/json
components:
  schemas:
    SuccessMessageSchema:
      properties:
        success_message:
          type: string
    UserSignUpSchema:
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    UserLoginSchema:
      properties:
        email:
          type: string
        password:
          type: string
    UserInfoSchema:
      properties:
        username:
          type: string
        user_roles:
          type: array
          items:
            type: string
        email:
          type: string
    UserInfoPageSchema:
      properties:
        items:
          type: array
          items:
            "$ref": "#/components/schemas/UserInfoSchema"
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
